### ISSUE TITLE
Crash at Server startup

### ISSUE THREAD

**Issue by lukiono** [EwyBoy/Bibliotheca#1]
Greetings,

Bibliotheca crashes the server on startup

Steps: Start the server and wait for the crash on loadup 

MC Version: 1.12.2
Mod Version: 1.0.3
Forge Version: 1.12.2-14.23.0.2542
Foamfix 0.8.1 Anarchy also used

Crash report:
https://ybin.me/p/90f6835e5da80276#99+KPAsMUK3azRFNTlwUkiA5kc2SkOS6acQjIFwip7w=

Kind regards

**Comment by EwyBoy** [comment]
Gonna look closer into this. Thanks for the report.

**Comment by EwyBoy** [comment]
It should be fixed now.
Download version 1.0.4 of Bibliotheca [here](https://minecraft.curseforge.com/projects/bibliotheca/files/2500471)
Download version 1.1.1 of ITank [here](https://minecraft.curseforge.com/projects/itank/files/2500474)

**Comment by EwyBoy** [comment]
This is fixed now. Grab the latest and greatest version of both mods.
