### ISSUE TITLE
Crash with bibliotheca on server

### ISSUE THREAD

**Issue by twoworlds** [EwyBoy/Bibliotheca#12]
Hi,
I just added iTank and Bibliotheca to my modpack. (MC 1.16.5, Forge 36.0.46). The client launches without a problem, but the server crashes on startup, here is the crashlog.

https://pastebin.com/Bkt5ZcxS

**Comment by EwyBoy** [comment]
Thanks for the report. I will look into it now.

**Comment by EwyBoy** [comment]
Fixed. Thanks for reporting!

Updated builds can be found here:
  https://www.curseforge.com/minecraft/mc-mods/bibliotheca/files/3227291
  https://www.curseforge.com/minecraft/mc-mods/itank/files/3227294

**Comment by papaworld** [comment]
Hello Sir, with the updated versions:
Bibliotheca-1.16.5-1.5.1.jar
ITank-1.16.5-1.3.1.jar
FML 36.0.46

I'm getting game launch crash - Bibliotheca has failed to load correctly - java.lang.NoSuchFieldError: LOOT_CONDITION_TYPE

Thank you... look forward to using your mod.
