### ISSUE TITLE
[1.18] NoSuchMethod net.minecraft.world.level.block.entity.BlockEntity.save

### ISSUE THREAD

**Issue by CanadianBaconBoi** [EwyBoy/Bibliotheca#16]
https://github.com/EwyBoy/Bibliotheca/blob/d3ac50a90bae6f28b670695ca2661df9788ec210/src/main/java/com/ewyboy/bibliotheca/util/ItemStacker.java#L32

`net.minecraft.world.level.block.entity.BlockEntity.save(CompoundTag)` has been removed in 1.18.1. Bibliotheca should change to use one of `saveId(CompoundTag)`, `saveAdditional(CompoundTag)`, or `saveMetadata(CompoundTag)`.

**Comment by EwyBoy** [comment]
Completely forgot about it, will fix asap

**Comment by EwyBoy** [comment]
Thanks, pushed an update for both this and ITank.
