### ISSUE TITLE
What's the goal with TileEntityLoader.TILE_ENTITIES?

### ISSUE THREAD

**Issue by gabizou** [EwyBoy/Bibliotheca#2]
Looking at an issue that was raised on [SpongeForge](https://github.com/SpongePowered/SpongeForge/issues/3024), I'm just wondering what the goal of "registering" a `TileEntity` by it's [`toString()`](https://github.com/EwyBoy/Bibliotheca/blob/2eed18c072532e64ff2fc7c0628c28f39b0cb777/src/main/java/com/ewyboy/bibliotheca/common/loaders/TileEntityLoader.java#L47-L51) which is based on the instance of the `TileEntity`, not it's class type... On looking further, there's no actual usage of the [map that is being used to store these instances](https://github.com/EwyBoy/Bibliotheca/blob/2eed18c072532e64ff2fc7c0628c28f39b0cb777/src/main/java/com/ewyboy/bibliotheca/common/loaders/TileEntityLoader.java#L16), so I have to ask: What's the purpose? Since it's currently a dead map being used, might just want to remove it entirely...

**Comment by EwyBoy** [comment]
Hey, sorry. I am pushing an update fixing this issue. Sorry for the trouble.
